/*
 * FullScreen Background  v1.6
 *
 * Copyright 2013-2019, LambertGroup
 *
 */

 (function(e){function Z(a,b,c){c.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(c.origWidth/c.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(c.origWidth/c.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("px")),
 newCss+="line-height:"+lineHeight/(c.origWidth/c.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(c.origWidth/c.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var f=a.attr("data-final-left"),g=a.attr("data-final-top");c.responsive&&(f=parseInt(f/(c.origWidth/c.width),10),g=parseInt(g/(c.origWidth/c.width),10));c=1;1==b.isVideoPlaying&&(c=0);a.animate({opacity:c,
 left:f+"px",top:g+"px"},1E3*a.attr("data-duration"),function(){1==b.isVideoPlaying&&e(b.currentImg.attr("data-text-id")).children().css("opacity",0)})}function M(a,b,c,f){e(a.currentImg.attr("data-text-id")).css("display","block");c=e(a.currentImg.attr("data-text-id")).children();var g=0;currentText_arr=[];c.each(function(){currentText_arr[g]=e(this);var c=currentText_arr[g].attr("data-initial-left"),f=currentText_arr[g].attr("data-initial-top");b.responsive&&(c=parseInt(c/(b.origWidth/b.width),10),
 f=parseInt(f/(b.origWidth/b.width),10));currentText_arr[g].css({left:c+"px",top:f+"px",opacity:parseInt(currentText_arr[g].attr("data-fade-start"),10)/100});var h=currentText_arr[g];setTimeout(function(){Z(h,a,b)},1E3*currentText_arr[g].attr("data-delay"));g++})}function O(a,b,c,f,g,k){K();-1==a&&(a=0);var m=e(g[a]),h=b.horizontalPosition;void 0!=m.attr("data-horizontalPosition")&&""!=m.attr("data-horizontalPosition")&&(h=m.attr("data-horizontalPosition"));g=b.verticalPosition;void 0!=m.attr("data-verticalPosition")&&
 ""!=m.attr("data-verticalPosition")&&(g=m.attr("data-verticalPosition"));f=f[a].split(";");b.width100Proc&&!b.height100Proc&&(f[0]/=b.origWidth/b.width,f[1]/=b.origWidth/b.width);m=f[0];if(b.width100Proc&&b.height100Proc&&1<m){m=k.winWidth;var x=m*f[1]/f[0];x<k.winHeight&&(x=k.winHeight,m=x*f[0]/f[1]);f[0]=parseInt(m,10);f[1]=parseInt(x,10)}a=e("#contentHolderUnit_"+a,c).find("img:first");switch(h){case "left":c=0;break;case "center":c=(b.width-f[0])/2;break;case "right":c=b.width-f[0];break;default:c=
 0}switch(g){case "top":g=-2;break;case "center":g=(b.height-f[1])/2;break;case "bottom":g=b.height-f[1]+2;break;default:g=0}1>=f[0]&&1>=f[1]?a.css({width:f[0]+"px",height:f[1]+"px",left:parseInt(c,10)+"px",top:parseInt(g,10)+"px",opacity:b.initialOpacity}):a.css({width:f[0]+"px",height:f[1]+"px","margin-left":parseInt(c,10)+"px","margin-top":parseInt(g,10)+"px",opacity:b.initialOpacity})}function S(a,b){nowx=(new Date).getTime();!a.mouseOverBanner&&b.showCircleTimer&&(a.ctx.clearRect(0,0,a.canvas.width,
 a.canvas.height),a.ctx.beginPath(),a.ctx.globalAlpha=b.behindCircleAlpha/100,a.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,2*Math.PI,!1),a.ctx.lineWidth=b.circleLineWidth+2,a.ctx.strokeStyle=b.behindCircleColor,a.ctx.stroke(),a.ctx.beginPath(),a.ctx.globalAlpha=b.circleAlpha/100,a.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,(a.timeElapsed+nowx-a.arcInitialTime)/1E3*2/b.autoPlay*Math.PI,!1),a.ctx.lineWidth=
 b.circleLineWidth,a.ctx.strokeStyle=b.circleColor,a.ctx.stroke())}function E(a,b,c,f,g,k,m,h,x,n,l,v,w,D,r,q,t){var F=!0;if(!c.loop&&b.current_img_no+a>=f||!c.loop&&0>b.current_img_no+a||2>f)F=!1;F&&!b.slideIsRunning&&(b.slideIsRunning=!0,e(".newFS",n).contents().unwrap(),b.arcInitialTime=(new Date).getTime(),b.timeElapsed=0,c.showCircleTimer&&(clearInterval(b.intervalID),b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=c.behindCircleAlpha/100,b.ctx.arc(c.circleRadius+
 2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth+2,b.ctx.strokeStyle=c.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=c.circleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,0,!1),b.ctx.lineWidth=c.circleLineWidth,b.ctx.strokeStyle=c.circleColor,b.ctx.stroke(),b.intervalID=setInterval(function(){S(b,c)},125)),b.bottomNavClicked||(b.previous_current_img_no=
 b.current_img_no),b.bottomNavClicked=!1,e(b.currentImg.attr("data-text-id")).css("display","none"),"bullets"==c.skin&&e(g[b.current_img_no]).removeClass("bottomNavButtonON"),"bullets"!=c.skin&&e(w[b.current_img_no]).css({"border-color":c.thumbsBorderColorOFF}),l.css("display","none"),b.current_img_no=b.current_img_no+a>=f?0:0>b.current_img_no+a?f-1:b.current_img_no+a,"bullets"==c.skin&&e(g[b.current_img_no]).addClass("bottomNavButtonON"),"bullets"!=c.skin&&(e(w[b.current_img_no]).css({"border-color":c.thumbsBorderColorON}),
 currentCarouselLeft=D.css("left").substr(0,D.css("left").lastIndexOf("px")),0===b.current_img_no||b.current_img_no===f-1?L(0,D,r,q,c,f,t,b):L(1001,D,r,q,c,f,t,b)),c.fadeSlides?(e("#contentHolderUnit_"+b.current_img_no,n).css({opacity:1,"z-index":0,display:"block"}),e("#contentHolderUnit_"+b.previous_current_img_no,n).css({"z-index":1,display:"block"}),e("#contentHolderUnit_"+b.previous_current_img_no,n).animate({opacity:0},800,"easeOutQuad",function(){b.slideIsRunning=!1;c.fadeSlides&&(e("#contentHolderUnit_"+
 b.current_img_no,n).css({"z-index":1}),e("#contentHolderUnit_"+b.previous_current_img_no,n).css({"z-index":0,display:"none"}));b.currentImg=e(k[b.current_img_no]);"true"==b.currentImg.attr("data-video")&&l.css("display","block");"true"==e(k[b.previous_current_img_no]).attr("data-video")&&(e("#contentHolderUnit_"+b.previous_current_img_no,n).html(e(k[b.previous_current_img_no]).html()),O(b.previous_current_img_no,c,n,v,k,b));M(b,c,m,h);0<c.autoPlay&&1<f&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),
 b.timeoutID=setTimeout(function(){E(1,b,c,f,g,k,m,h,x,n,l,v,w,D,r,q,t)},1E3*c.autoPlay))})):x.animate({left:-1*b.current_img_no*c.width+"px"},800,"easeOutQuad",function(){b.slideIsRunning=!1;b.currentImg=e(k[b.current_img_no]);"true"==b.currentImg.attr("data-video")&&l.css("display","block");"true"==e(k[b.previous_current_img_no]).attr("data-video")&&(e("#contentHolderUnit_"+b.previous_current_img_no,n).html(e(k[b.previous_current_img_no]).html()),O(b.previous_current_img_no,c,n,v,k,b));M(b,c,m,h);
 0<c.autoPlay&&1<f&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),b.timeoutID=setTimeout(function(){E(1,b,c,f,g,k,m,h,x,n,l,v,w,D,r,q,t)},1E3*c.autoPlay))}),-1!=K()&&c.texturePath&&e(".texture_over_image",n).css("display","block"))}function L(a,b,e,f,g,k,m,h){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?(h.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:"+="+a*h.carouselStep},500,"easeOutCubic",function(){H(h,b,e,f,g,k,m);h.isCarouselScrolling=
 !1})):currentCarouselLeft!=-1*Math.floor(h.current_img_no/g.numberOfThumbsPerScreen)*h.carouselStep&&(h.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:-1*Math.floor(h.current_img_no/g.numberOfThumbsPerScreen)*h.carouselStep},500,"easeOutCubic",function(){H(h,b,e,f,g,k,m);h.isCarouselScrolling=!1}))}function H(a,b,e,f,g,k,m){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>currentCarouselLeft?e.hasClass("carouselLeftNavDisabled")&&e.removeClass("carouselLeftNavDisabled"):
 e.addClass("carouselLeftNavDisabled");Math.abs(currentCarouselLeft-a.carouselStep)<(2*a.thumbBorderWidth+m.width()+a.thumbMarginLeft)*k?f.hasClass("carouselRightNavDisabled")&&f.removeClass("carouselRightNavDisabled"):f.addClass("carouselRightNavDisabled")}function T(a,b,c,f,g,k,m,h,x,n,l){"bullets"!=b.skin&&(l.css({top:b.height+"px","margin-top":parseInt(b.thumbsWrapperMarginTop/(b.origWidth/b.width),10)+"px",height:parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)+"px"}),bgTopCorrection=
 0,m.css("background-position","0px "+((l.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),h.css("background-position","0px "+((l.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),n.css("width",b.width-m.width()-h.width()),b.origWidthThumbsHolderVisibleWrapper=b.origWidth-m.width()-h.width(),g.css({width:parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/n.width()),10)+"px",height:parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/n.width()),10)+"px"}),
 e(".thumbsHolder_ThumbOFF",f).find("img:first").css({width:g.width()+"px",height:g.height()+"px"}),a.thumbMarginLeft=Math.floor((l.width()-m.width()-h.width()-(2*a.thumbBorderWidth+x.width())*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),thumb_i=-1,k.children().each(function(){thumb_i++;theThumb=e(this);0>=thumb_i?theThumb.css("margin-left",Math.floor((l.width()-m.width()-h.width()-(a.thumbMarginLeft+(2*a.thumbBorderWidth+theThumb.width()))*(b.numberOfThumbsPerScreen-1)-(2*a.thumbBorderWidth+
 theThumb.width()))/2)+"px"):theThumb.css("margin-left",a.thumbMarginLeft+"px")}),a.carouselStep=(2*a.thumbBorderWidth+x.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen);if(b.numberOfThumbsPerScreen>=c)switch(b.bottomNavPos){case "left":n.css("left",b.bottomNavLateralMargin+a.thumbMarginLeft+"px");break;case "right":n.css("left",b.width-(2*a.thumbBorderWidth+g.width()+a.thumbMarginLeft)*c-b.bottomNavLateralMargin+"px");break;default:n.css("left",parseInt((l.width()-(2*a.thumbBorderWidth+x.width()+
 a.thumbMarginLeft)*c)/2,10)+"px")}}function U(a,b,c,f){b=b.videoProportionWidth;void 0!=e(c[a.current_img_no]).attr("data-videoProportionWidth")&&""!=e(c[a.current_img_no]).attr("data-videoProportionWidth")&&(b=e(c[a.current_img_no]).attr("data-videoProportionWidth"));a=parseInt(1280/b*9,10);windowW=e(window).width()+1;windowH=e(window).height();c=1/(1280/windowW);a/windowH<1280/windowW&&(c=1/(a/windowH));16!=b&&(c+=.11);e("iframe",f).css({width:1280*c+"px",height:a*c+"px",left:parseInt((windowW-
 1280*c)/2,10)+"px",top:parseInt((windowH-a*c)/2,10)+"px"})}function K(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}function aa(a){var b=!1;a=a.substr(a.length-4).toLowerCase();if(".jpg"==a||".png"==a||".gif"==a)b=!0;return b}e.fn.fullscreen_background=function(a){a=e.extend({},e.fn.fullscreen_background.defaults,a);return this.each(function(){var b=e(this);responsiveWidth=
 b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=e(window).width(),responsiveHeight=e(window).height());a.origWidth=a.width;a.fadeSlides||--a.origWidth;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/
 a.origHeight)));var c=e("<div></div>").addClass("fullscreen_background").addClass(a.skin),f=e('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>      </div>  <div class="contentHolderVisibleWrapper"><div class="contentHolder"></div></div>   <div class="playOver"></div>  <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div> <canvas class="mycanvas"></canvas>');b.wrap(c);a.texturePath&&(b.append('<div class="texture_over_image" />'),
 e(".texture_over_image",g).css({background:"url("+a.texturePath+")"}));b.after(f);var g=b.parent(".fullscreen_background");a.setAsBg&&g.wrap('<div class="setAsBg" />');var k=e(".bannerControls",g),m=e(".contentHolderVisibleWrapper",g),h=e(".contentHolder",g);c=e('<div class="bottomNav"></div>');b.after(c);a.showAllControllers||k.css("display","none");var x=e(".leftNav",g),n=e(".rightNav",g);x.css("display","none");n.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(x.css("display","block"),
 n.css("display","block"));var l=e(".bottomNav",g),v;"bullets"==a.skin&&(l.css({display:"block",top:a.height+"px"}),a.width100Proc&&a.height100Proc?l.css("margin-top",a.thumbsWrapperMarginTop+"px"):l.css("margin-top",a.thumbsWrapperMarginTop/(a.origWidth/a.width)+"px"));a.showBottomNav||l.css("display","none");a.showOnInitBottomNav||l.css("left","-5000px");var w=e(".thumbsHolderWrapper",g),D=e(".thumbsHolderVisibleWrapper",g),r=e(".thumbsHolder",g);var q=e('<div class="carouselLeftNav"></div>');var t=
 e('<div class="carouselRightNav"></div>');w.append(q);w.append(t);t.css("right","0");r.css("width",q.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||w.css({opacity:0,display:"none"});"bullets"!=a.skin&&w.css("margin-top",parseInt(a.thumbsWrapperMarginTop/(a.origWidth/a.width),10)+"px");var F=K();if(-1!=F&&a.texturePath)e(".texture_over_image",g).on("click",function(){var b=e(y[d.current_img_no]);if(void 0!=b.attr("data-link")&&""!=b.attr("data-link")){var c=a.target;void 0!=b.attr("data-target")&&
 ""!=b.attr("data-target")&&(c=b.attr("data-target"));"_blank"==c?window.open(b.attr("data-link")):window.location=b.attr("data-link")}else"true"==b.attr("data-video")&&z.click()});a.enableTouchScreen&&g.swipe({swipe:function(e,c,f,ba,l){d.effectIsRunning||E("right"==c?-1:1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u)}});var z=e(".playOver",g);z.css({left:parseInt((a.width-z.width())/2,10)+"px",top:parseInt((a.height-z.height())/2,10)+"px"});var d={current_img_no:0,currentImg:0,previous_current_img_no:0,slideIsRunning:!1,
 mouseOverBanner:!1,isVideoPlaying:!1,bottomNavClicked:!1,current_imgInside:"",windowWidth:0,carouselStep:0,thumbBorderWidth:0,thumbMarginLeft:0,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,canvas:"",ctx:"",bannerRatio:a.origWidth/a.origHeight,msiInterval:"",msiInitialTime:(new Date).getTime(),winWidth:0,winHeight:0};d.winWidth=e(window).width();d.winHeight=e(window).height();d.canvas=e(".mycanvas",g)[0];d.canvas.width=2*a.circleRadius+4*a.circleLineWidth;d.canvas.height=
 2*a.circleRadius+4*a.circleLineWidth;-1!=F&&9>F&&(a.showCircleTimer=!1);a.showCircleTimer&&(d.ctx=d.canvas.getContext("2d"));var G=[],Q=0;g.width(a.width);g.height(a.height);m.width(a.width);m.height(a.height);h.width(a.width);h.height(a.height);k.css("margin-top",parseInt((a.height-x.height())/2,10)+"px");var p=0,y=b.find("ul:first").children(),I,H=0,C,N=0,W=0,J,u,X=0,Y=0;y.each(function(){d.currentImg=e(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));d.currentImg.is("li")&&
 (p++,myzindex=0,mydisplay="none",1==p&&(myzindex=1,mydisplay="block"),I=e('<div class="contentHolderUnit" rel="'+(p-1)+'" id="contentHolderUnit_'+(p-1)+'">'+d.currentImg.html()+"</div>"),1>=y.length&&d.currentImg.html(""),a.fadeSlides?I.css({position:"absolute",top:0,left:0,"z-index":myzindex,display:mydisplay}):I.css({position:"relative","float":"left"}),I.width(a.width),I.height(a.height),h.append(I),H+=a.width,d.current_img_no=p-1,J=e("#contentHolderUnit_"+d.current_img_no,g).find("img:first"),
 G[p-1]=J.width()+";"+J.height(),O(p-1,a,g,G,y,d),"bullets"==a.skin&&(C=e('<div class="bottomNavButtonOFF" rel="'+(p-1)+'"></div>'),l.append(C),N+=parseInt(C.css("padding-left").substring(0,C.css("padding-left").length-2),10)+C.width(),W=parseInt((l.height()-parseInt(C.css("height").substring(0,C.css("height").length-2)))/2,10),C.css("margin-top",W+"px")),"bullets"!=a.skin&&(image_name=e(y[p-1]).attr("data-bottom-thumb"),u=e('<div class="thumbsHolder_ThumbOFF" rel="'+(p-1)+'"><img src="'+image_name+
 '"></div>'),r.append(u),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-q.width()-t.width())/(2*d.thumbBorderWidth+u.width()))-1),a.origThumbW=u.width(),a.origThumbH=u.height(),a.origthumbsHolderWrapperH=w.height(),d.thumbBorderWidth=u.css("borderLeftWidth").substr(0,u.css("borderLeftWidth").lastIndexOf("px")),d.thumbMarginLeft=Math.floor((a.origWidth-q.width()-t.width()-(2*d.thumbBorderWidth+u.width())*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-
 1))),r.css("width",r.width()+d.thumbMarginLeft+(2*d.thumbBorderWidth+u.width())+"px"),X=parseInt((w.height()-parseInt(u.css("height").substring(0,u.css("height").length-2)))/2,10)),Y=a.fadeSlides?0:parseInt((p-1)*a.width,10),h.append(e(d.currentImg.attr("data-text-id"))),e(d.currentImg.attr("data-text-id")).css({width:b.width()+"px",left:Y,top:k.css("top")}))});1>=p&&(a.autoPlay=0,a.showNavArrows=!1,a.showOnInitNavArrows=!1,a.showBottomNav=!1,a.showOnInitBottomNav=!1,x.css("display","none"),n.css("display",
 "none"),l.css("display","none"));c=a.thumbsWrapperBg;aa(a.thumbsWrapperBg)&&(c="url("+a.thumbsWrapperBg+")");w.css({background:c});h.width(H);l.width(N);if(a.showOnInitBottomNav)switch(a.bottomNavPos){case "left":l.css("left",a.bottomNavLateralMargin+"px");break;case "right":l.css("left",parseInt(g.width()-N,10)-a.bottomNavLateralMargin+"px");break;default:l.css("left",parseInt((g.width()-N)/2,10)+"px")}"bullets"!=a.skin&&(D.css({width:a.origWidth-q.width()-t.width(),left:q.width()+"px"}),d.carouselStep=
 (2*d.thumbBorderWidth+u.width()+d.thumbMarginLeft)*a.numberOfThumbsPerScreen,q.addClass("carouselLeftNavDisabled"),a.numberOfThumbsPerScreen>=p&&(t.addClass("carouselRightNavDisabled"),q.css("display","none"),t.css("display","none"),D.css("left",parseInt((w.width()-(2*d.thumbBorderWidth+u.width()+d.thumbMarginLeft)*p)/2,10)+"px")),w.css("top",a.height+"px"),e(".thumbsHolder_ThumbOFF",g).find("img:first"),a.origthumbsHolder_MarginTop=X);var A=e(".thumbsHolder_ThumbOFF",g);A.css({"border-color":a.thumbsBorderColorOFF});
 T(d,a,p,g,A,r,q,t,u,D,w);e("iframe",g).each(function(){var a=navigator.userAgent.toLowerCase(),b=e(this).attr("src"),d="?wmode=transparent";-1!=b.indexOf("?")&&(d="&wmode=transparent");-1!=a.indexOf("ipad")||-1!=a.indexOf("iphone")||-1!=a.indexOf("ipod")||-1!=a.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?d+="&mute=1":-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&
 (d+="&mute=1");e(this).attr("src",b+d)});d.current_img_no=0;a.fadeSlides&&e("#contentHolderUnit_"+d.current_img_no,g).css({"z-index":1});d.currentImg=e(y[0]);c=g.find("img:first");if(c[0].complete)e(".myloader",g).css("display","none"),M(d,a,b,k);else c.on("load",function(){e(".myloader",g).css("display","none");M(d,a,b,k)});g.on("mouseenter",function(){a.pauseOnMouseOver&&(d.mouseOverBanner=!0,clearTimeout(d.timeoutID),nowx=(new Date).getTime(),d.timeElapsed+=nowx-d.arcInitialTime);a.autoHideNavArrows&&
 a.showNavArrows&&(x.css("display","block"),n.css("display","block"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?l.css({display:"block"}):0>a.thumbsWrapperMarginTop&&d.isVideoPlaying||!a.showBottomNav||(w.css({display:"block"}),w.stop().animate({opacity:1},500,"swing",function(){})))});g.on("mouseleave",function(){a.pauseOnMouseOver&&(d.mouseOverBanner=!1,nowx=(new Date).getTime());a.autoHideNavArrows&&a.showNavArrows&&!d.isVideoPlaying&&(x.css("display","none"),n.css("display","none"));
 a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?l.css("display","none"):w.stop().animate({opacity:0},300,"swing",function(){}));if(0<a.autoPlay&&1<p&&!d.isVideoPlaying&&a.pauseOnMouseOver){clearTimeout(d.timeoutID);d.arcInitialTime=(new Date).getTime();var e=parseInt(1E3*a.autoPlay-(d.timeElapsed+nowx-d.arcInitialTime),10);d.timeoutID=setTimeout(function(){E(1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u)},e)}});c=e(".contentHolderUnit",h);-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome")&&
 -1==navigator.userAgent.indexOf("Android")?c.css("z-index","1"):-1!=navigator.userAgent.indexOf("Chrome")&&-1==navigator.userAgent.indexOf("Android")&&c.css("z-index","1");c.on("click",function(){var b=e(this).attr("rel");"true"==e(y[d.current_img_no]).attr("data-video")&&(b!=d.current_img_no?d.isVideoPlaying=!1:z.click());var c=e(y[d.current_img_no]);void 0!=c.attr("data-link")&&b==d.current_img_no&&""!=c.attr("data-link")&&(b=a.target,void 0!=c.attr("data-target")&&""!=c.attr("data-target")&&(b=
 c.attr("data-target")),"_blank"==b?window.open(c.attr("data-link")):window.location=c.attr("data-link"))});z.on("click",function(){z.css("display","none");clearTimeout(d.timeoutID);J=e("#contentHolderUnit_"+d.current_img_no,g).find("img:first");J.css("display","none");e(d.currentImg.attr("data-text-id")).children().css("opacity",0);d.isVideoPlaying=!0;0>a.thumbsWrapperMarginTop&&(w.css("display","none"),"bullets"==a.skin&&l.css("display","none"));a.showCircleTimer&&(clearInterval(d.intervalID),d.ctx.clearRect(0,
 0,d.canvas.width,d.canvas.height),d.ctx.beginPath(),d.ctx.globalAlpha=0,d.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,0,!1),d.ctx.lineWidth=a.circleLineWidth+2,d.ctx.strokeStyle=a.behindCircleColor,d.ctx.stroke(),d.ctx.beginPath(),d.ctx.globalAlpha=0,d.ctx.arc(a.circleRadius+2*a.circleLineWidth,a.circleRadius+2*a.circleLineWidth,a.circleRadius,0,0,!1),d.ctx.lineWidth=a.circleLineWidth,d.ctx.strokeStyle=a.circleColor,d.ctx.stroke());-1!=F&&a.texturePath&&
 e(".texture_over_image",g).css("display","none")});x.on("click",function(){d.slideIsRunning||(d.isVideoPlaying=!1,a.showBottomNav&&(w.css({opacity:1,display:"block"}),"bullets"==a.skin&&l.css("display","block")),clearTimeout(d.timeoutID),E(-1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u))});n.on("click",function(){d.slideIsRunning||(d.isVideoPlaying=!1,a.showBottomNav&&(w.css({opacity:1,display:"block"}),"bullets"==a.skin&&l.css("display","block")),clearTimeout(d.timeoutID),E(1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u))});
 var R=!1;e(window).on("resize",function(){var c=K();doResizeNow=!0;var f=navigator.userAgent.toLowerCase();-1!=f.indexOf("android")&&(0==a.windowOrientationScreenSize0&&0==window.orientation&&(a.windowOrientationScreenSize0=e(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=e(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=e(window).height()),a.windowOrientationScreenSize0&&
 0==window.orientation&&e(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=!1),a.windowOrientationScreenSize90&&90==window.orientation&&e(window).height()>a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&e(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==d.windowWidth&&(doResizeNow=!1,d.windowWidth=e(window).width()));-1!=c&&9==c&&0==d.windowWidth&&(doResizeNow=!1);d.windowWidth==e(window).width()?(doResizeNow=
 !1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):d.windowWidth=e(window).width();if(-1!=f.indexOf("ipad")||-1!=f.indexOf("iphone")||-1!=f.indexOf("ipod")||-1!=f.indexOf("webos"))doResizeNow=!0;a.responsive&&doResizeNow&&(!1!==R&&clearTimeout(R),R=setTimeout(function(){var c=d,f=a,n=p,P=y,v=g,C=z,F=G,V=A,I=B,H=u,J=N;if(f.width100Proc&&f.height100Proc&&!f.setAsBg){var K=e("body").css("overflow");e("body").css("overflow",
 "hidden")}c.winWidth=e(window).width();c.winHeight=e(window).height();responsiveWidth=b.parent().parent().width();responsiveHeight=b.parent().parent().height();f.responsiveRelativeToBrowser&&(responsiveWidth=e(window).width(),responsiveHeight=e(window).height());f.width100Proc&&(f.width=responsiveWidth);f.height100Proc&&(f.height=responsiveHeight);if(f.origWidth!=responsiveWidth||f.width100Proc){f.origWidth>responsiveWidth||f.width100Proc?f.width=responsiveWidth:f.width100Proc||(f.width=f.origWidth);
 f.height100Proc||(f.height=f.width/c.bannerRatio);v.width(f.width);v.height(f.height);m.width(f.width);m.height(f.height);h.width(f.width);h.height(f.height);k.css("margin-top",parseInt((f.height-x.height())/2,10)+"px");contentHolderUnit=e(".contentHolderUnit",v);contentHolderUnit.width(f.width);contentHolderUnit.height(f.height);holderWidth=f.width*n;for(i=0;i<n;i++){O(i,f,v,F,P,c);var L=f.fadeSlides?0:parseInt(i*f.width,10);e(e(P[i]).attr("data-text-id")).css({width:b.width()+"px",left:L,top:k.css("top")})}h.width(holderWidth);
 if("bullets"==f.skin){switch(f.bottomNavPos){case "left":l.css({left:f.bottomNavLateralMargin+"px",top:f.height+"px"});break;case "right":l.css({left:parseInt(v.width()-J,10)-f.bottomNavLateralMargin+"px",top:f.height+"px"});break;default:l.css({left:parseInt((v.width()-J)/2,10)+"px",top:f.height+"px"})}f.width100Proc&&f.height100Proc||l.css("margin-top",parseInt(f.thumbsWrapperMarginTop/(f.origWidth/f.width),10)+"px")}else T(c,f,n,v,V,r,q,t,H,D,w);C.css({left:parseInt((f.width-C.width())/2,10)+"px",
 top:parseInt((f.height-C.height())/2,10)+"px"});2<=n?(clearTimeout(c.timeoutID),E(1,c,f,n,I,P,b,k,h,v,C,F,V,r,q,t,H)):(e(".newFS",v).contents().unwrap(),e(c.currentImg.attr("data-text-id")).css("display","none"),M(c,f,b,k));f.width100Proc&&f.height100Proc&&f.setAsBg&&U(c,f,P,v)}f.width100Proc&&f.height100Proc&&!f.setAsBg&&e("body").css("overflow",K)},300))});var B=e(".bottomNavButtonOFF",g);"bullets"==a.skin&&(B.on("click",function(){if(!d.slideIsRunning){d.isVideoPlaying=!1;var c=e(this).attr("rel");
 d.current_img_no!=c&&(e(B[d.current_img_no]).removeClass("bottomNavButtonON"),d.previous_current_img_no=d.current_img_no,d.bottomNavClicked=!0,d.current_img_no=c-1,clearTimeout(d.timeoutID),E(1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u))}}),B.on("mouseenter",function(){var b=e(this),d=b.attr("rel");if(a.showPreviewThumbs){v=e('<div class="bottomOverThumb"></div>');b.append(v);var c=e(y[d]).attr("data-bottom-thumb"),f=e(y[Q]).attr("data-bottom-thumb"),g=80,h=-80;Q>d&&(g=-80,h=80);v.html("");v.html('<div class="innerBottomOverThumb"><img src="'+
 f+'"style="margin:0px;" id="oldThumb"><img src="'+c+'" style="margin-top:-80px; margin-left:'+g+'px;" id="newThumb"></div>');e("#newThumb").stop().animate({marginLeft:"0px"},150,function(){v.html('<div class="innerBottomOverThumb"><img src="'+c+'"></div>')});e("#oldThumb").stop().animate({marginLeft:h+"px"},150,function(){});Q=d}b.addClass("bottomNavButtonON")}),B.on("mouseleave",function(){var b=e(this),c=b.attr("rel");a.showPreviewThumbs&&v.remove();d.current_img_no!=c&&b.removeClass("bottomNavButtonON")}));
 A.on("mousedown",function(){if(!d.slideIsRunning){arrowClicked=!0;d.isVideoPlaying=!1;var c=e(this).attr("rel");d.current_img_no!=c&&(e(A[d.current_img_no]).css({"border-color":a.thumbsBorderColorOFF}),d.previous_current_img_no=d.current_img_no,d.bottomNavClicked=!0,d.current_img_no=c-1,clearTimeout(d.timeoutID),E(1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u))}});A.on("mouseup",function(){arrowClicked=!1});A.on("mouseenter",function(){var b=e(this);b.attr("rel");b.css({"border-color":a.thumbsBorderColorON})});
 A.on("mouseleave",function(){var b=e(this),c=b.attr("rel");d.current_img_no!=c&&b.css({"border-color":a.thumbsBorderColorOFF})});q.on("click",function(){d.isCarouselScrolling||(currentCarouselLeft=r.css("left").substr(0,r.css("left").lastIndexOf("px")),0>currentCarouselLeft&&L(1,r,q,t,a,p,u,d))});t.on("click",function(){d.isCarouselScrolling||(currentCarouselLeft=r.css("left").substr(0,r.css("left").lastIndexOf("px")),Math.abs(currentCarouselLeft-d.carouselStep)<(2*d.thumbBorderWidth+u.width()+d.thumbMarginLeft)*
 p&&L(-1,r,q,t,a,p,u,d))});a.width100Proc&&a.height100Proc&&a.setAsBg&&U(d,a,y,g);"bullets"==a.skin&&e(B[d.current_img_no]).addClass("bottomNavButtonON");e(A[d.current_img_no]).css({"border-color":a.thumbsBorderColorON});0<a.autoPlay&&1<p&&(a.showCircleTimer&&(d.intervalID=setInterval(function(){S(d,a)},125)),d.timeoutID=setTimeout(function(){E(1,d,a,p,B,y,b,k,h,g,z,G,A,r,q,t,u)},1E3*a.autoPlay));"true"==e(y[d.current_img_no]).attr("data-video")&&z.css("display","block")})};e.fn.fullscreen_background.defaults=
 {skin:"bullets",width:1920,height:600,width100Proc:!0,height100Proc:!0,autoPlay:6,fadeSlides:!0,loop:!0,setAsBg:!0,texturePath:"",horizontalPosition:"center",verticalPosition:"center",initialOpacity:1,target:"_blank",pauseOnMouseOver:!1,showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:8,circleLineWidth:4,circleColor:"#ffffff",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:20,responsive:!0,responsiveRelativeToBrowser:!0,numberOfThumbsPerScreen:0,bottomNavPos:"right",bottomNavLateralMargin:0,
 thumbsWrapperMarginTop:-110,thumbsWrapperBg:"",thumbsBorderColorON:"#000000",thumbsBorderColorOFF:"#7a7a7a",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!1,showPreviewThumbs:!0,enableTouchScreen:!0,absUrl:"",videoProportionWidth:16,videoProportionHeight:9,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origthumbsHolderWrapperH:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,
 windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
